site_name: LaTeX Lecture Note
theme:
  name: material
  features:
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Japanese
      link: /
      lang: ja
nav:
  - はじめに: JP/index.md
  - 文書設定:
    - \documentclass: JP/doc_setting/document.md
    - \usepackage: JP/doc_setting/package.md
  - 爆速コンパイル in Windows: 
    - はじめに: JP/latex_with_wsl/introduction_wsl.md
    - VSCodeの設定: JP/latex_with_wsl/vscode.md
  - Package Template: JP/mat_template.md